// Universal Game Step System
export const UNIVERSAL_GAME_STEPS = {
  // Pre-game
  GAME_SETUP: "game_setup",
  GAME_START: "game_start",

  // Stage 1 - Startup Capital
  STAGE1_INIT: "game_s1_init",
  STAGE1_HUSTLE_PICK: "game_s1_hustle_pick",
  STAGE1_HUSTLE_REVEAL: "game_s1_hustle_reveal",
  STAGE1_QUESTIONS_PREP: "game_s1_questions_prep",
  STAGE1_QUESTIONS: "game_s1_questions",
  STAGE1_QUESTION_REVEAL: "game_s1_question_reveal",
  STAGE1_TIMER_RUNNING: "game_s1_timer_start",
  STAGE1_BIDS_REVEAL: "game_s1_bids_reveal",
  STAGE1_RESULTS: "game_s1_results",

  // Stage 2 - Opportunity
  STAGE2_INIT: "game_s2_init",
  STAGE2_PREP: "game_s2_prep",
  STAGE2_QUESTIONS: "game_s2_questions",
  STAGE2_QUESTION_REVEAL: "game_s2_question_reveal",
  STAGE2_TIMER_RUNNING: "game_s2_timer_running",
  STAGE2_OPTIONS_REVEAL: "game_s2_options_reveal",
  STAGE2_RESULTS: "game_s2_results",

  // Stage 3 - Dud or Opportunity
  STAGE3_INIT: "stage3_init",
  STAGE3_PREP: "stage3_prep",
  STAGE3_PICKS_START: "stage3_picks_start",
  STAGE3_END: "stage3_end",

  // Stage 4 - Final Round
  STAGE4_INIT: "stage4_init",
  STAGE4_PREP: "stage4_prep",
  STAGE4_RAFFLE: "stage4_raffle",

  // Game End
  GAME_END: "game_end",
} as const


export type UniversalGameStep = (typeof UNIVERSAL_GAME_STEPS)[keyof typeof UNIVERSAL_GAME_STEPS]

// Step progression mapping
export const STEP_PROGRESSION: Record<UniversalGameStep, UniversalGameStep | null> = {
  [UNIVERSAL_GAME_STEPS.GAME_SETUP]: UNIVERSAL_GAME_STEPS.GAME_START,
  [UNIVERSAL_GAME_STEPS.GAME_START]: UNIVERSAL_GAME_STEPS.STAGE1_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE1_INIT]: UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK,
  [UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK]: UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_REVEAL]: UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS_PREP]: UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS,
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS]: UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVEAL]: UNIVERSAL_GAME_STEPS.STAGE1_TIMER_RUNNING,
  [UNIVERSAL_GAME_STEPS.STAGE1_TIMER_RUNNING]: UNIVERSAL_GAME_STEPS.STAGE1_BIDS_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_BIDS_REVEAL]: UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS, // Loop back for more questions
  [UNIVERSAL_GAME_STEPS.STAGE1_RESULTS]: UNIVERSAL_GAME_STEPS.STAGE2_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE2_INIT]: UNIVERSAL_GAME_STEPS.STAGE2_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE2_PREP]: UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS,
  [UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS]: UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVEAL]: UNIVERSAL_GAME_STEPS.STAGE2_TIMER_RUNNING,
  [UNIVERSAL_GAME_STEPS.STAGE2_TIMER_RUNNING]: UNIVERSAL_GAME_STEPS.STAGE2_OPTIONS_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE2_OPTIONS_REVEAL]: UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS, // Loop back for more questions
  [UNIVERSAL_GAME_STEPS.STAGE2_RESULTS]: UNIVERSAL_GAME_STEPS.STAGE3_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE3_INIT]: UNIVERSAL_GAME_STEPS.STAGE3_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE3_PREP]: UNIVERSAL_GAME_STEPS.STAGE3_PICKS_START,
  [UNIVERSAL_GAME_STEPS.STAGE3_PICKS_START]: UNIVERSAL_GAME_STEPS.STAGE3_END,
  [UNIVERSAL_GAME_STEPS.STAGE3_END]: UNIVERSAL_GAME_STEPS.STAGE4_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE4_INIT]: UNIVERSAL_GAME_STEPS.STAGE4_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE4_PREP]: UNIVERSAL_GAME_STEPS.STAGE4_RAFFLE,
  [UNIVERSAL_GAME_STEPS.STAGE4_RAFFLE]: UNIVERSAL_GAME_STEPS.GAME_END,
  [UNIVERSAL_GAME_STEPS.GAME_END]: null,
}