// Universal Game Step System
export const UNIVERSAL_GAME_STEPS = {
  // Pre-game
  GAME_SETUP: "game_setup",
  GAME_START: "game_start",

  // Stage 1 - Startup Capital
  STAGE1_INIT: "game_s1_init",
  STAGE1_HUSTLE_PICK: "game_s1_hustle_pick",
  STAGE1_HUSTLE_PICK_TIME_ELAPSE: "game_s1_hustle_pick_time_elapse",
  STAGE1_HUSTLE_REVEAL: "game_s1_hustle_reveal",
  STAGE1_QUESTIONS_PREP: "game_s1_questions_prep",
  STAGE1_QUESTIONS: "game_s1_questions",
  STAGE1_QUESTION_REVEAL: "game_s1_question_reveal",
  STAGE1_QUESTION_REVERT: "game_s1_question_revert",
  STAGE1_QUESTION_RESULT_REVEAL: "game_s1_question_answer",
  STAGE1_TIMER_RUNNING: "game_s1_timer_start",
  STAGE1_BIDS_REVEAL: "game_s1_question_bids_reveal",
  STAGE1_RESULTS: "game_s1_results_reveal",

  // Stage 2 - Opportunity
  STAGE2_INIT: "game_s2_init",
  STAGE2_PREP: "game_s2_prep",
  STAGE2_QUESTIONS: "game_s2_questions",
  STAGE2_QUESTION_REVEAL: "game_s2_question_reveal",
  STAGE2_QUESTION_REVERT: "game_s2_question_revert",
  STAGE2_TIMER_RUNNING: "game_s2_timer_start",
  STAGE2_OPTIONS_REVEAL: "game_s2_options_reveal",
  STAGE2_OPTIONS_SELECT_REVEAL: "game_s2_question_options_select_reveal",
  STAGE2_QUESTION_RESULT_REVEAL: "game_s2_question_answer",
  STAGE2_RESULTS: "game_s2_results_reveal",

  // Stage 3 - Dud or Opportunity
  STAGE3_INIT: "game_s3_init",
  STAGE3_PREP: "game_s3_prep",
  STAGE3_PICKS_START: "game_s3_start",
  STAGE3_END: "game_s3_end",

  // Stage 4 - Final Round
  STAGE4_INIT: "game_s4_init",
  STAGE4_PREP: "game_s4_prep",
  STAGE4_RAFFLE: "geme_s4_start",
  STAGE4_BALL_PICK: "ball_picked",

  // Game End
  GAME_END: "game_end",
} as const;

export type UniversalGameStep = typeof UNIVERSAL_GAME_STEPS[keyof typeof UNIVERSAL_GAME_STEPS];

// Step progression mapping
export const STEP_PROGRESSION: Record<
  UniversalGameStep,
  UniversalGameStep | null
> = {
  [UNIVERSAL_GAME_STEPS.GAME_SETUP]: UNIVERSAL_GAME_STEPS.GAME_START,
  [UNIVERSAL_GAME_STEPS.GAME_START]: UNIVERSAL_GAME_STEPS.STAGE1_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE1_INIT]: UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK,
  [UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK]:
    UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK_TIME_ELAPSE,
  [UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK_TIME_ELAPSE]:
    UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS_PREP]:
    UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS,
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS]:
    UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE1_TIMER_RUNNING,
  [UNIVERSAL_GAME_STEPS.STAGE1_TIMER_RUNNING]:
    UNIVERSAL_GAME_STEPS.STAGE1_BIDS_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_BIDS_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_RESULT_REVEAL, // Loop back for more questions
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_RESULT_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVERT]:
    UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE1_RESULTS]: UNIVERSAL_GAME_STEPS.STAGE2_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE2_INIT]: UNIVERSAL_GAME_STEPS.STAGE2_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE2_PREP]: UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS,
  [UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS]:
    UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE2_TIMER_RUNNING,
  [UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVERT]:
    UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE2_TIMER_RUNNING]:
    UNIVERSAL_GAME_STEPS.STAGE2_OPTIONS_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE2_OPTIONS_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS, // Loop back for more questions
  [UNIVERSAL_GAME_STEPS.STAGE2_OPTIONS_SELECT_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS, // Loop back for more questions
  [UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_RESULT_REVEAL]:
    UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVEAL,
  [UNIVERSAL_GAME_STEPS.STAGE2_RESULTS]: UNIVERSAL_GAME_STEPS.STAGE3_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE3_INIT]: UNIVERSAL_GAME_STEPS.STAGE3_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE3_PREP]: UNIVERSAL_GAME_STEPS.STAGE3_PICKS_START,
  [UNIVERSAL_GAME_STEPS.STAGE3_PICKS_START]: UNIVERSAL_GAME_STEPS.STAGE3_END,
  [UNIVERSAL_GAME_STEPS.STAGE3_END]: UNIVERSAL_GAME_STEPS.STAGE4_INIT,
  [UNIVERSAL_GAME_STEPS.STAGE4_INIT]: UNIVERSAL_GAME_STEPS.STAGE4_PREP,
  [UNIVERSAL_GAME_STEPS.STAGE4_PREP]: UNIVERSAL_GAME_STEPS.STAGE4_RAFFLE,
  [UNIVERSAL_GAME_STEPS.STAGE4_RAFFLE]: UNIVERSAL_GAME_STEPS.STAGE4_BALL_PICK,
  [UNIVERSAL_GAME_STEPS.STAGE4_BALL_PICK]: UNIVERSAL_GAME_STEPS.GAME_END,
  [UNIVERSAL_GAME_STEPS.GAME_END]: null,
};

export const getStageFromStep = (step: UniversalGameStep): string => {
  switch (step) {
    case UNIVERSAL_GAME_STEPS.STAGE1_INIT:
    case UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK:
    case UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_PICK_TIME_ELAPSE:
    case UNIVERSAL_GAME_STEPS.STAGE1_HUSTLE_REVEAL:
    case UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS_PREP:
    case UNIVERSAL_GAME_STEPS.STAGE1_QUESTIONS:
    case UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_REVEAL:
    case UNIVERSAL_GAME_STEPS.STAGE1_TIMER_RUNNING:
    case UNIVERSAL_GAME_STEPS.STAGE1_BIDS_REVEAL:
    case UNIVERSAL_GAME_STEPS.STAGE1_QUESTION_RESULT_REVEAL:
      return "STAGE_ONE";

    case UNIVERSAL_GAME_STEPS.STAGE2_INIT:
    case UNIVERSAL_GAME_STEPS.STAGE2_PREP:
    case UNIVERSAL_GAME_STEPS.STAGE2_QUESTIONS:
    case UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_REVEAL:
    case UNIVERSAL_GAME_STEPS.STAGE2_TIMER_RUNNING:
    case UNIVERSAL_GAME_STEPS.STAGE2_OPTIONS_REVEAL:
    case UNIVERSAL_GAME_STEPS.STAGE2_OPTIONS_SELECT_REVEAL:
    case UNIVERSAL_GAME_STEPS.STAGE2_QUESTION_RESULT_REVEAL:
      return "STAGE_TWO";

    case UNIVERSAL_GAME_STEPS.STAGE3_INIT:
    case UNIVERSAL_GAME_STEPS.STAGE3_PREP:
    case UNIVERSAL_GAME_STEPS.STAGE3_PICKS_START:
      return "STAGE_THREE";

    case UNIVERSAL_GAME_STEPS.STAGE4_INIT:
    case UNIVERSAL_GAME_STEPS.STAGE4_PREP:
      return "STAGE_FOUR";

    default:
      return "STAGE_ONE";
  }
};

const getStageFirstStep = (stage: string) => {

};

export const BONUS_FLIP_STYLE = {
  backgroundColor: "#001144",
  rayColor: "#00BFFF",
  innerCircleColor: "#002266",
  textColor: "#00BFFF",
  cornerColor: "#0088CC",
  fontFamily: "Arial",
  fontSize: 16,
  labelBackgroundColor: "#000822",
  textStrokeWidth: 1,
  textStrokeColor: "#001133",
};

export const MISS_FLIP_STYLE = {
  backgroundColor: "#440022",
  rayColor: "#FF1493",
  innerCircleColor: "#660033",
  textColor: "#FF1493",
  cornerColor: "#AA0055",
  fontFamily: "Arial",
  fontSize: 16,
  labelBackgroundColor: "#220011",
  textStrokeWidth: 1,
  textStrokeColor: "#330022",
};

export const PASS_CARD_STYLE = {
  backgroundColor: "#FFD700",
  rayColor: "#FFF700",
  innerCircleColor: "#FFED4E",
  textColor: "#000000",
  cornerColor: "#FFB000",
  fontFamily: "Arial",
  fontSize: 18,
  labelBackgroundColor: "#FFE55C",
  textStrokeWidth: 2,
  textStrokeColor: "#B8860B",
};

// Instant cash card styles
export const INSTANT_CASH_STYLES = {
  FIVE_K: {
    backgroundColor: "#006600",
    rayColor: "#00FF00",
    innerCircleColor: "#008800",
    textColor: "#00FF00",
    cornerColor: "#00AA00",
    fontFamily: "Arial",
    fontSize: 16,
    labelBackgroundColor: "#004400",
    textStrokeWidth: 1,
    textStrokeColor: "#002200",
  },
  TEN_K: {
    backgroundColor: "#004400",
    rayColor: "#00DD00",
    innerCircleColor: "#006600",
    textColor: "#00DD00",
    cornerColor: "#008800",
    fontFamily: "Arial",
    fontSize: 16,
    labelBackgroundColor: "#002200",
    textStrokeWidth: 1,
    textStrokeColor: "#001100",
  },
  TWENTY_K: {
    backgroundColor: "#002200",
    rayColor: "#00BB00",
    innerCircleColor: "#004400",
    textColor: "#00BB00",
    cornerColor: "#006600",
    fontFamily: "Arial",
    fontSize: 16,
    labelBackgroundColor: "#001100",
    textStrokeWidth: 1,
    textStrokeColor: "#000800",
  },
};
